### ISSUE TITLE
Install erela.js as a development dependency

### ISSUE THREAD

**Issue by acollierr17** [Spiderjockey02/erela.js-facebook#1]
Hey, thanks for making this neat plugin! I wanted to inform you that `erela.js` should be installed as a development dependency instead of a regular dependency. This is due to transitive dependencies and the conflicts that happen when using `erela.js` in an actual project and the one used in a plugin like this one.

For more information and backstory, feel free to check this issue raised over on the official `erela.js` repository: https://github.com/MenuDocs/erela.js/issues/77

**Comment by Spiderjockey02** [comment]
Sorry for the long wait but this issue should be resolved now
