### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Tomato6966** [Spiderjockey02/erela.js-facebook#3]
I get query.replace is not a function
so i make query to a string via.
String(query) (in your search function)

then i get:
connect ECONNREFUSED 127.0.0.1:80

pls fix

**Comment by birongliu** [comment]
Look like you didn't open lavalink;

**Comment by Spiderjockey02** [comment]
Please provide as much information as possible; like the link you used, the full error message (in console) etc.

> connect ECONNREFUSED 127.0.0.1:80

This has nothing to do with this plugin

**Comment by Tomato6966** [comment]
i have lavalink open
i have erela.js 
i have erela.js-spotify and erela.js-deezer
but with facebook it all crashes

**Comment by Spiderjockey02** [comment]
We can't do anything without error messages

**Comment by Tomato6966** [comment]
I don't have them anymore

**Comment by Spiderjockey02** [comment]
so.... what do you want me to do?

**Comment by Tomato6966** [comment]
Literally i told the whole error code

**Comment by Tomato6966** [comment]
imma get the error code

**Comment by Tomato6966** [comment]
![image](https://user-images.githubusercontent.com/68145571/131001844-a4e2d1f5-8e07-4936-9082-1560466a4275.png)

**Comment by Spiderjockey02** [comment]
What facebook link did u use to get this error?

**Comment by Tomato6966** [comment]
Code: 
```js
res = await client.manager.search({
      query: "https://www.facebook.com/peopleareawesome/videos/best-videos-of-the-week/1426881677361006/",
      source: "youtube"
}, message.author);
```

**Comment by Tomato6966** [comment]
I just realised
on windows it works, but on linux with ipv6 routing not

**Comment by Tomato6966** [comment]
no need to reply anymore!
